import { ReactNode } from 'react'
import LoginStatus from './loginStatus'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

type Props = {
    title: string
    children: ReactNode
}

const Layout = ({ title, children }: Props) => {
    return (
        <>
            <Head>
                <title>{`${title ? title : ''} - todo app`}</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <div className='layout'>
                <header className={styles.header}>
                    <h3 className={styles.logo}>
                        <Link href='/'>
                            <a>create todo app</a>
                        </Link>
                    </h3>
                    <div className={styles.login_status_wrapper}>
                        <LoginStatus />
                    </div>
                </header>
                <main className={styles.main}>{children}</main>
                <footer className={styles.footer}>
                    <h4>@todo app</h4>
                </footer>
            </div>
        </>
    )
}

export default Layout
